### ISSUE TITLE
Rebuild `v4ex/v4ex-web-search` to be Cloudflare Pages Native Web App

### ISSUE THREAD

**Issue by v4ex-inc** [v4ex/com.v4ex.Search#8]
# Tasks
* [x] 1. Utilize `wrangler@beta` for local development.
* [x] 2. Clean up local git branches after merge in GitHub.
* [ ] 3. Single source of truth state management for Search results, page amount, current page.

## 1. Utilize `wrangler@beta` for local development.

<details><summary>Details</summary>

1. Use `npm i -g wrangler@beta` instead of `% npm i -g @cloudflare/wrangler@beta` for https://blog.cloudflare.com/wrangler-v2-beta/
2. https://nextjs.org/docs/advanced-features/static-html-export
2.1. `next build && next export`
2.2. https://stackoverflow.com/questions/31318068/shell-script-to-remove-a-file-if-it-already-exist/31318262
3. `next/image` issue on Cloudflare Pages
3.1. https://nextjs.org/docs/messages/no-img-element
3.2. https://nextjs.org/docs/basic-features/image-optimization
3.3. https://nextjs.org/docs/api-reference/next/image#loader
4. https://nextjs.org/docs/api-reference/next/router
5. Possible issue: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
```zsh
% export NODE_OPTIONS=--openssl-legacy-provider
```
6. https://www.twilio.com/blog/react-choose-functional-components
6.1. https://reactjs.org/docs/hooks-reference.html#usestate
6.2. https://stackoverflow.com/questions/58101018/react-calling-a-method-on-load-only-once
7. https://nextjs.org/docs/api-reference/next/router
8. Test
```zsh
% npm run export
% ln -s $(pwd)/functions $(pwd)/out
% cd out
% npx wrangler@beta pages dev .
```
9. https://www.codegrepper.com/code-examples/shell/next+js+port+3000+is+already+in+use
10. https://miniflare.dev/storage/kv
10.1. KV stored in `./mf/kv/*`

----------------------------------------------
</details>

## 2. Clean up local git branches after merge in GitHub.

<details><summary>Details</summary>

1. https://www.fizerkhan.com/blog/posts/clean-up-your-local-branches-after-merge-and-delete-in-github
2. https://stackoverflow.com/questions/14005854/what-to-do-with-branch-after-merge

⚡ Conclusion
-------------
1. Assume `WIP` branch was merged into `main` on GitHub.
2. `% git checkout main`
3. `% git branch -d WIP`

----------------------------------------------
</details>

## 3. Single source of truth state management for Search results, page amount, current page.

1. https://stackoverflow.com/questions/47182888/what-does-the-single-source-of-truth-mean
![](https://i.stack.imgur.com/xKTy3.png)
2. https://redux.js.org/introduction/getting-started
2.1. https://redux.js.org/tutorials/fundamentals/part-1-overview
3. https://reactjs.org/docs/lifting-state-up.html
4. https://blog.bitsrc.io/redux-react-alternatives-c1733793a339
5. https://reactjs.org/docs/getting-started.html
5.1. https://reactjs.org/tutorial/tutorial.html
5.2. https://reactjs.org/community/support.html

----------------------------------------------
